name: manage-azure-policy-711110e0
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/policies/Flow_logs_should_be_enabled_for_every_network_security_group_27960feb-a23c-4577-8d36-ef8b5f35e0be/**'
#      - .github/workflows/manage-azure-policy-711110e0.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_711110e0}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/policies/Flow_logs_should_be_enabled_for_every_network_security_group_27960feb-a23c-4577-8d36-ef8b5f35e0be/**
